### ISSUE TITLE
String formatting error making project un-runnable on Android Studio 3.1.4

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-DrawableTinting#1]
I'm having issues getting this going.  It's probably some issue with my Android Studio configuration, but I'm not experienced enough to know.  I have a stackoverflow question on it that explains further:

https://stackoverflow.com/questions/52307125/why-doesnt-this-drawable-tinting-android-code-sample-work-out-of-the-box

I tried commenting out the offending lines... which I assumed simply setText in a textview... and now the app runs... but it doesn't seem to do what it claims... as the textview is a different color than the button... and neither one changes color or appearance as a result of being focused/clicked, etc.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
